sudo: required
services:
  - docker

before_install:
  - docker build -t davidka79/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davidka79/react-test npm test

language: generic

after_success:
  - docker build -t davidka79/multi-client ./client
  - docker build -t davidka79/multi-nginx ./nginx
  - docker build -t davidka79/multi-server ./server
  - docker build -t davidka79/multi-worker ./worker


