sudo: required
services:
  - docker

before_install:
  - docker build -t davidka79/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davidka79/react-test npm test

language: generic

after_success:
  - docker build -t davidka79/multi-client ./client
  - docker build -t davidka79/multi-nginx ./nginx
  - docker build -t davidka79/multi-server ./server
  - docker build -t davidka79/multi-worker ./worker
  ## login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ## Take those images and push them to docker hub
  - docker push davidka79/multi-client
  - docker push davidka79/multi-nginx
  - docker push davidka79/multi-server
  - docker push davidka79/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-322431154880"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY